server:
  port: ${SERVER_PORT:8130}

logging:
  level:
    org.springframework: INFO
    com.example.accesscontrolmanager: DEBUG

spring:
  application:
    name: access-control-manager
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:access_control}
  flyway:
    enabled: true
    schemas: access_control
    placeholders:
      bootstrap-system-user-id: ${SYSTEM_ADMIN_SYSTEMUSER_ID:a0000000-0000-0000-0000-000000000001}
      data-creator-system-user-id: ${SYSTEM_ADMIN_SYSTEMUSER_ID:a0000000-0000-0000-0000-000000000001}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/userdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9000/realms/system}
  cloud:
    config:
      enabled: false

application:
  name: "@project.name"
  description: "@project.description@"
  version: "@project.version"
  env: ${ENVIRONMENT:local}

cache:
  expire-after: ${CACHE_EXPIRE_AFTER:60}
  expiry-units: ${CACHE_EXPIRY_UNITS:MINUTES}
  max: ${CACHE_MAX_SIZE:1000}

access-control:
  security:
    manager-url: ${ACM_URL:http://localhost:8130}
    system-user-id-claim: systemUserId
    fail-on-error: false

clients:
  clients:
    user-manager:
      base-url: ${USER_MANAGER_URL:http://localhost:8080}

keycloak-manager:
  url: ${KM_URL:http://localhost:8210}