server:
  port: ${SERVER_PORT:8130}

logging:
  level:
    org.springframework: INFO
    com.example.accesscontrolmanager: DEBUG

spring:
  application:
    name: access-control-manager
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:access_control}
  flyway:
    enabled: true
    schemas: access_control
    placeholders:
      bootstrap-system-user-id: ${SYSTEM_ADMIN_SYSTEMUSER-ID:9a908a6d-77hq-38sj-28ka-9aa90tg9h56f}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/userdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

application:
  name: "@project.name"
  description: "@project.description@"
  version: "@project.version"
  env: ${ENVIRONMENT:local}

cache:
  expire-after: ${CACHE_EXPIRE_AFTER:60}
  expiry-units: ${CACHE_EXPIRY_UNITS:MINUTES}
  max: ${CACHE_MAX_SIZE:1000}

clients:
  clients:
    user-manager:
      base-url: ${USER_MANAGER_URL:http://localhost:8080}